import { useQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { CalendarClock, CarFront, CircleAlert, FileCheck2, FileClock, FileWarning, ShieldAlert, TrafficCone, Wrench } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CentralPendencias } from "@/components/central-pendencias";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { fetchDashboard, fetchDiasAlerta, vehicleMap } from "@/lib/queries";
import { formatDate, situacaoVencimento, SITUACAO_LABEL } from "@/lib/format";

export const Route = createFileRoute("/_authenticated/_app/dashboard")({ head: () => ({ meta: [{ title: "Dashboard — Controle de Frota" }, { name: "description", content: "Visão geral da frota, documentos, agenda e ocorrências." }, { property: "og:title", content: "Dashboard — Controle de Frota" }, { property: "og:description", content: "Visão geral da frota, documentos, agenda e ocorrências." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: DashboardPage });

function DashboardPage() {
  const { data, isLoading, error } = useQuery({ queryKey: ["dashboard"], queryFn: fetchDashboard });
  const { data: diasAlerta = 30 } = useQuery({ queryKey: ["dias-alerta"], queryFn: fetchDiasAlerta, staleTime: 5 * 60_000 });
  if (isLoading) return <div className="py-20 text-center text-muted-foreground">Carregando indicadores…</div>;
  if (error || !data) return <div className="surface-card p-6 text-destructive">Não foi possível carregar os indicadores.</div>;
  const plates = vehicleMap(data.veiculos); const counts = data.vencimentos.reduce<Record<string, number>>((a, r) => { const k = situacaoVencimento(r.data_vencimento, r.status, diasAlerta); a[k] = (a[k] ?? 0) + 1; return a; }, {});
  const cards = [["Veículos", data.veiculos.length, "Ativos", CarFront, "text-primary bg-primary/10"], ["Regulares", counts["DENTRO DA VALIDADE"] ?? 0, "Documentações", FileCheck2, "text-success bg-success/10"], ["Próximos", counts["PROXIMO DO VENCIMENTO"] ?? 0, "Até 30 dias", FileClock, "text-warning-foreground bg-warning/20"], ["Vencidos", counts["VENCIDO"] ?? 0, "Exigem atenção", FileWarning, "text-destructive bg-destructive/10"], ["Em processo", counts["EM PROCESSO"] ?? 0, "Renovação", CircleAlert, "text-info bg-info/10"], ["Manutenção", data.counts.manutencoesEmAndamento, "Em andamento", Wrench, "text-primary bg-primary/10"], ["Sinistros", data.counts.sinistrosEmAndamento, "Em andamento", ShieldAlert, "text-destructive bg-destructive/10"], ["Multas", data.counts.multasPendentes, "Pendentes", TrafficCone, "text-warning-foreground bg-warning/20"]] as const;
  const upcoming = data.vencimentos.filter(r => ["VENCIDO", "PROXIMO DO VENCIMENTO"].includes(situacaoVencimento(r.data_vencimento, r.status, diasAlerta))).slice(0, 7);
  return <><PageHeader title="Dashboard" description="Visão geral dos veículos, obrigações e atividades da operação." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, detail, Icon, tone]) => <Card key={label} className="rounded-lg shadow-card"><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><span className={`flex size-10 items-center justify-center rounded-md ${tone}`}><Icon className="size-5" /></span></CardContent></Card>)}</div><div className="mt-6"><CentralPendencias vencidos={counts["VENCIDO"] ?? 0} proximos={counts["PROXIMO DO VENCIMENTO"] ?? 0} agendadas={data.counts.agendaAgendada} sinistros={data.counts.sinistrosEmAndamento} manutencoes={data.counts.manutencoesEmAndamento} anexos={data.counts.anexos} multasIndicacao={data.counts.multasIndicacao} /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><Card className="rounded-lg shadow-card"><CardHeader><CardTitle className="text-base">Vencimentos prioritários</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Veículo</TableHead><TableHead>Documento</TableHead><TableHead>Vencimento</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{upcoming.map(r => { const s = situacaoVencimento(r.data_vencimento, r.status, diasAlerta); return <TableRow key={r.id}><TableCell className="font-semibold">{r.veiculo_id ? plates.get(r.veiculo_id) ?? "—" : "—"}</TableCell><TableCell>{r.descricao || r.tipo_codigo || "—"}</TableCell><TableCell>{formatDate(r.data_vencimento)}</TableCell><TableCell><StatusBadge value={SITUACAO_LABEL[s]} /></TableCell></TableRow>; })}</TableBody></Table></CardContent></Card><Card className="rounded-lg shadow-card"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarClock className="size-4 text-primary" />Próxima agenda</CardTitle></CardHeader><CardContent className="space-y-3">{data.agenda.length ? data.agenda.map(i => <div key={i.id} className="flex items-start justify-between gap-3 border-b pb-3 last:border-0"><div><p className="text-sm font-semibold">{i.titulo || i.atividade}</p><p className="mt-1 text-xs text-muted-foreground">{i.veiculo_id ? plates.get(i.veiculo_id) ?? "Sem veículo" : "Sem veículo"} · {formatDate(i.data)} {i.hora?.slice(0,5)}</p></div><StatusBadge value={i.status} /></div>) : <p className="text-sm text-muted-foreground">Nenhum compromisso agendado.</p>}</CardContent></Card></div></>;
}