/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/_app/configuracoes'
import { Route as AuthenticatedAppDadosComplementaresRouteImport } from './routes/_authenticated/_app/dados-complementares'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppDocumentacaoRouteImport } from './routes/_authenticated/_app/documentacao'
import { Route as AuthenticatedAppManutencaoRouteImport } from './routes/_authenticated/_app/manutencao'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/_app/relatorios'
import { Route as AuthenticatedAppSinistrosRouteImport } from './routes/_authenticated/_app/sinistros'
import { Route as AuthenticatedAppVeiculosRouteImport } from './routes/_authenticated/_app/veiculos'
import { Route as AuthenticatedAppVencimentosRouteImport } from './routes/_authenticated/_app/vencimentos'
import { Route as AuthenticatedAppVeiculosVeiculoIdRouteImport } from './routes/_authenticated/_app/veiculos.$veiculoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDadosComplementaresRoute =
  AuthenticatedAppDadosComplementaresRouteImport.update({
    id: '/dados-complementares',
    path: '/dados-complementares',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentacaoRoute =
  AuthenticatedAppDocumentacaoRouteImport.update({
    id: '/documentacao',
    path: '/documentacao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppManutencaoRoute =
  AuthenticatedAppManutencaoRouteImport.update({
    id: '/manutencao',
    path: '/manutencao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSinistrosRoute =
  AuthenticatedAppSinistrosRouteImport.update({
    id: '/sinistros',
    path: '/sinistros',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVeiculosRoute =
  AuthenticatedAppVeiculosRouteImport.update({
    id: '/veiculos',
    path: '/veiculos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVencimentosRoute =
  AuthenticatedAppVencimentosRouteImport.update({
    id: '/vencimentos',
    path: '/vencimentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVeiculosVeiculoIdRoute =
  AuthenticatedAppVeiculosVeiculoIdRouteImport.update({
    id: '/$veiculoId',
    path: '/$veiculoId',
    getParentRoute: () => AuthenticatedAppVeiculosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/dados-complementares': typeof AuthenticatedAppDadosComplementaresRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documentacao': typeof AuthenticatedAppDocumentacaoRoute
  '/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/sinistros': typeof AuthenticatedAppSinistrosRoute
  '/veiculos': typeof AuthenticatedAppVeiculosRouteWithChildren
  '/vencimentos': typeof AuthenticatedAppVencimentosRoute
  '/veiculos/$veiculoId': typeof AuthenticatedAppVeiculosVeiculoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/dados-complementares': typeof AuthenticatedAppDadosComplementaresRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/documentacao': typeof AuthenticatedAppDocumentacaoRoute
  '/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/sinistros': typeof AuthenticatedAppSinistrosRoute
  '/veiculos': typeof AuthenticatedAppVeiculosRouteWithChildren
  '/vencimentos': typeof AuthenticatedAppVencimentosRoute
  '/veiculos/$veiculoId': typeof AuthenticatedAppVeiculosVeiculoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/_app/dados-complementares': typeof AuthenticatedAppDadosComplementaresRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/documentacao': typeof AuthenticatedAppDocumentacaoRoute
  '/_authenticated/_app/manutencao': typeof AuthenticatedAppManutencaoRoute
  '/_authenticated/_app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/_app/sinistros': typeof AuthenticatedAppSinistrosRoute
  '/_authenticated/_app/veiculos': typeof AuthenticatedAppVeiculosRouteWithChildren
  '/_authenticated/_app/vencimentos': typeof AuthenticatedAppVencimentosRoute
  '/_authenticated/_app/veiculos/$veiculoId': typeof AuthenticatedAppVeiculosVeiculoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dados-complementares'
    | '/dashboard'
    | '/documentacao'
    | '/manutencao'
    | '/relatorios'
    | '/sinistros'
    | '/veiculos'
    | '/vencimentos'
    | '/veiculos/$veiculoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dados-complementares'
    | '/dashboard'
    | '/documentacao'
    | '/manutencao'
    | '/relatorios'
    | '/sinistros'
    | '/veiculos'
    | '/vencimentos'
    | '/veiculos/$veiculoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/_app/configuracoes'
    | '/_authenticated/_app/dados-complementares'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/documentacao'
    | '/_authenticated/_app/manutencao'
    | '/_authenticated/_app/relatorios'
    | '/_authenticated/_app/sinistros'
    | '/_authenticated/_app/veiculos'
    | '/_authenticated/_app/vencimentos'
    | '/_authenticated/_app/veiculos/$veiculoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/configuracoes': {
      id: '/_authenticated/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dados-complementares': {
      id: '/_authenticated/_app/dados-complementares'
      path: '/dados-complementares'
      fullPath: '/dados-complementares'
      preLoaderRoute: typeof AuthenticatedAppDadosComplementaresRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/documentacao': {
      id: '/_authenticated/_app/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof AuthenticatedAppDocumentacaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/manutencao': {
      id: '/_authenticated/_app/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedAppManutencaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/relatorios': {
      id: '/_authenticated/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/sinistros': {
      id: '/_authenticated/_app/sinistros'
      path: '/sinistros'
      fullPath: '/sinistros'
      preLoaderRoute: typeof AuthenticatedAppSinistrosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/veiculos': {
      id: '/_authenticated/_app/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedAppVeiculosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/vencimentos': {
      id: '/_authenticated/_app/vencimentos'
      path: '/vencimentos'
      fullPath: '/vencimentos'
      preLoaderRoute: typeof AuthenticatedAppVencimentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/veiculos/$veiculoId': {
      id: '/_authenticated/_app/veiculos/$veiculoId'
      path: '/$veiculoId'
      fullPath: '/veiculos/$veiculoId'
      preLoaderRoute: typeof AuthenticatedAppVeiculosVeiculoIdRouteImport
      parentRoute: typeof AuthenticatedAppVeiculosRoute
    }
  }
}

interface AuthenticatedAppVeiculosRouteChildren {
  AuthenticatedAppVeiculosVeiculoIdRoute: typeof AuthenticatedAppVeiculosVeiculoIdRoute
}

const AuthenticatedAppVeiculosRouteChildren: AuthenticatedAppVeiculosRouteChildren =
  {
    AuthenticatedAppVeiculosVeiculoIdRoute:
      AuthenticatedAppVeiculosVeiculoIdRoute,
  }

const AuthenticatedAppVeiculosRouteWithChildren =
  AuthenticatedAppVeiculosRoute._addFileChildren(
    AuthenticatedAppVeiculosRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppDadosComplementaresRoute: typeof AuthenticatedAppDadosComplementaresRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDocumentacaoRoute: typeof AuthenticatedAppDocumentacaoRoute
  AuthenticatedAppManutencaoRoute: typeof AuthenticatedAppManutencaoRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppSinistrosRoute: typeof AuthenticatedAppSinistrosRoute
  AuthenticatedAppVeiculosRoute: typeof AuthenticatedAppVeiculosRouteWithChildren
  AuthenticatedAppVencimentosRoute: typeof AuthenticatedAppVencimentosRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppDadosComplementaresRoute:
    AuthenticatedAppDadosComplementaresRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDocumentacaoRoute: AuthenticatedAppDocumentacaoRoute,
  AuthenticatedAppManutencaoRoute: AuthenticatedAppManutencaoRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppSinistrosRoute: AuthenticatedAppSinistrosRoute,
  AuthenticatedAppVeiculosRoute: AuthenticatedAppVeiculosRouteWithChildren,
  AuthenticatedAppVencimentosRoute: AuthenticatedAppVencimentosRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
