import { useQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Database, FileSpreadsheet, SlidersHorizontal } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { SpreadsheetImport } from "@/components/spreadsheet-import";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/_app/configuracoes")({ head: () => ({ meta: [{ title: "Configurações — Controle de Frota" }, { name: "description", content: "Parâmetros e cadastros auxiliares da gestão de frota." }, { property: "og:title", content: "Configurações — Controle de Frota" }, { property: "og:description", content: "Parâmetros e cadastros auxiliares da gestão de frota." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: SettingsPage });
function SettingsPage() {
  const { data } = useQuery({ queryKey: ["configuracoes"], queryFn: async () => { const [cfg, params] = await Promise.all([supabase.from("configuracoes").select("*").order("grupo").order("ordem"), supabase.from("parametros").select("*").order("chave")]); if (cfg.error || params.error) throw cfg.error || params.error; return { cfg: cfg.data ?? [], params: params.data ?? [] }; } });
  return <><PageHeader title="Configurações" description="Cadastros auxiliares e regras usadas pelo sistema." /><div className="grid gap-6 lg:grid-cols-3"><SettingsCard icon={Database} title="Tipos e opções" description="Documentos, manutenção, sinistros, responsáveis e status." count={data?.cfg.length ?? 0}>{data?.cfg.slice(0,6).map(c => <div key={c.id} className="flex justify-between border-b py-2 last:border-0"><span className="text-sm">{c.valor}</span><StatusBadge value={c.ativo ? "ATIVO" : "INATIVO"} /></div>)}</SettingsCard><SettingsCard icon={SlidersHorizontal} title="Parâmetros" description="Regras gerais e períodos de alerta." count={data?.params.length ?? 0}>{data?.params.map(p => <div key={p.chave} className="border-b py-2 last:border-0"><p className="text-sm font-medium">{p.chave}</p><p className="text-xs text-muted-foreground">{p.valor}</p></div>)}</SettingsCard><SettingsCard icon={FileSpreadsheet} title="Importação XLSX" description="Compare uma nova planilha antes de atualizar os registros." count={0}><SpreadsheetImport /></SettingsCard></div></>;
}
function SettingsCard({ icon: Icon, title, description, count, children }: { icon: typeof Database; title: string; description: string; count: number; children: React.ReactNode }) { return <Card className="rounded-lg"><CardHeader><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-md bg-primary/10 text-primary"><Icon className="size-5" /></span><span className="text-xs text-muted-foreground">{count} item(ns)</span></div><CardTitle className="pt-3 text-base">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card>; }