import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Download, FileSpreadsheet, Printer } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/page-header";
import { supabase } from "@/integrations/supabase/client";

const reports = [{ table: "vencimentos", title: "Vencimentos", description: "Prazos, responsáveis e situação documental." }, { table: "tipos_documento", title: "Documentações", description: "Catálogo de tipos documentais." }, { table: "agenda_eventos", title: "Agenda", description: "Atividades e compromissos agendados." }, { table: "sinistros", title: "Sinistros", description: "Ocorrências, seguros e valores." }, { table: "multas", title: "Multas", description: "Infrações, indicação de condutor, pagamentos e recursos." }, { table: "manutencoes", title: "Manutenções", description: "Ordens, oficinas, prazos e custos." }, { table: "veiculos", title: "Situação da frota", description: "Cadastro completo e situação dos veículos, incluindo vendidos." }, { table: "motoristas", title: "Motoristas", description: "Condutores cadastrados e validade de CNH." }, { table: "historico", title: "Histórico", description: "Registro auditável de alterações." }, { table: "valores_negociados", title: "Valores negociados", description: "Valores importados da planilha original." }, { table: "flutuante", title: "Flutuante", description: "Veículos temporários e movimentações." }] as const;

export const Route = createFileRoute("/_authenticated/_app/relatorios")({ head: () => ({ meta: [{ title: "Relatórios — Controle de Frota" }, { name: "description", content: "Relatórios e exportações da gestão de frota." }, { property: "og:title", content: "Relatórios — Controle de Frota" }, { property: "og:description", content: "Relatórios e exportações da gestão de frota." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ReportsPage });
function ReportsPage() {
  const [busy, setBusy] = useState("");
  const exportReport = async (table: typeof reports[number]["table"], title: string, format: "csv" | "xlsx") => { setBusy(`${table}-${format}`); const response = await supabase.from(table).select("*"); setBusy(""); if (response.error) { toast.error("Não foi possível gerar o relatório", { description: response.error.message }); return; } const rows = response.data ?? []; if (!rows.length) { toast.info("Este relatório não possui registros."); return; } const XLSX = await import("xlsx"); const sheet = XLSX.utils.json_to_sheet(rows); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, title.slice(0,31)); const safe = title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, "-"); if (format === "xlsx") XLSX.writeFile(book, `${safe}.xlsx`); else { const csv = XLSX.utils.sheet_to_csv(sheet); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `${safe}.csv`; a.click(); URL.revokeObjectURL(a.href); } };
  return <><PageHeader title="Relatórios" description="Exporte os dados operacionais ou prepare uma versão para impressão." actions={<Button variant="outline" onClick={() => window.print()}><Printer />Imprimir página</Button>} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{reports.map(report => <Card key={report.table} className="rounded-lg"><CardHeader><span className="mb-2 flex size-10 items-center justify-center rounded-md bg-primary/10 text-primary"><FileSpreadsheet className="size-5" /></span><CardTitle className="text-base">{report.title}</CardTitle><CardDescription>{report.description}</CardDescription></CardHeader><CardContent className="flex gap-2"><Button size="sm" variant="outline" disabled={busy.startsWith(report.table)} onClick={() => exportReport(report.table, report.title, "csv")}><Download />CSV</Button><Button size="sm" disabled={busy.startsWith(report.table)} onClick={() => exportReport(report.table, report.title, "xlsx")}><Download />XLSX</Button></CardContent></Card>)}</div></>;
}