import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Paperclip } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/integrations/supabase/client";
import { formatCurrency, formatDate, formatDateTime, formatNumber, situacaoVencimento, SITUACAO_LABEL } from "@/lib/format";

export const Route = createFileRoute("/_authenticated/_app/veiculos/$veiculoId")({ head: () => ({ meta: [{ title: "Ficha do veículo — Controle de Frota" }, { name: "description", content: "Ficha completa e histórico do veículo." }, { property: "og:title", content: "Ficha do veículo — Controle de Frota" }, { property: "og:description", content: "Ficha completa e histórico do veículo." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: VehicleDetail });

function VehicleDetail() {
  const { veiculoId } = Route.useParams();
  const { data, isLoading } = useQuery({ queryKey: ["veiculo", veiculoId], queryFn: async () => {
    const [vehicle, deadlines, maintenance, claims, technical, history, files] = await Promise.all([
      supabase.from("veiculos").select("*").eq("id", veiculoId).single(), supabase.from("vencimentos").select("*").eq("veiculo_id", veiculoId).order("data_vencimento"), supabase.from("manutencoes").select("*").eq("veiculo_id", veiculoId).order("data_abertura", { ascending: false }), supabase.from("sinistros").select("*").eq("veiculo_id", veiculoId).order("data", { ascending: false }), supabase.from("ficha_tecnica").select("*").eq("veiculo_id", veiculoId).maybeSingle(), supabase.from("historico").select("*").eq("veiculo_id", veiculoId).order("created_at", { ascending: false }), supabase.from("anexos").select("*").eq("entidade_id", veiculoId).order("created_at", { ascending: false }),
    ]); if (vehicle.error) throw vehicle.error; return { vehicle: vehicle.data, deadlines: deadlines.data ?? [], maintenance: maintenance.data ?? [], claims: claims.data ?? [], technical: technical.data, history: history.data ?? [], files: files.data ?? [] };
  } });
  if (isLoading || !data) return <div className="py-20 text-center text-muted-foreground">Carregando ficha…</div>;
  const v = data.vehicle; const details = [["Placa", v.placa], ["RENAVAM", v.renavam], ["Chassi", v.chassi], ["Marca", v.marca], ["Modelo", v.modelo], ["Ano fabricação", v.ano_fabricacao], ["Ano modelo", v.ano_modelo], ["Cor", v.cor], ["Tipo", v.tipo_veiculo], ["Categoria", v.categoria], ["Combustível", v.combustivel], ["Capacidade", v.capacidade], ["Quilometragem", v.quilometragem ? `${formatNumber(v.quilometragem, 0)} km` : null], ["Proprietário", v.proprietario], ["Unidade", v.unidade], ["Localização", v.localizacao], ["Aquisição", formatDate(v.data_aquisicao)], ["Valor aquisição", formatCurrency(v.valor_aquisicao)]];
  const tabClass = "h-10 shrink-0";
  return <><PageHeader title={v.placa} description={v.marca_modelo || [v.marca, v.modelo].filter(Boolean).join(" ") || "Veículo sem descrição"} actions={<><StatusBadge value={v.status} /><Button variant="outline" asChild><Link to="/veiculos"><ArrowLeft />Voltar</Link></Button></>} /><Tabs defaultValue="dados"><div className="overflow-x-auto"><TabsList className="h-auto w-max min-w-full justify-start"><TabsTrigger className={tabClass} value="dados">Dados gerais</TabsTrigger><TabsTrigger className={tabClass} value="documentacao">Documentação</TabsTrigger><TabsTrigger className={tabClass} value="manutencao">Manutenção</TabsTrigger><TabsTrigger className={tabClass} value="sinistros">Sinistros</TabsTrigger><TabsTrigger className={tabClass} value="ficha">Ficha técnica</TabsTrigger><TabsTrigger className={tabClass} value="historico">Histórico</TabsTrigger><TabsTrigger className={tabClass} value="anexos">Anexos</TabsTrigger></TabsList></div>
    <TabsContent value="dados"><Card className="rounded-lg"><CardContent className="grid gap-x-8 gap-y-5 p-6 sm:grid-cols-2 lg:grid-cols-3">{details.map(([label, value]) => <div key={String(label)}><p className="text-xs font-medium uppercase text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value || "—"}</p></div>)}{v.observacoes && <div className="sm:col-span-2 lg:col-span-3"><p className="text-xs font-medium uppercase text-muted-foreground">Observações</p><p className="mt-1 whitespace-pre-wrap text-sm">{v.observacoes}</p></div>}</CardContent></Card></TabsContent>
    <TabsContent value="documentacao"><Card className="rounded-lg"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Tipo</TableHead><TableHead>Descrição</TableHead><TableHead>Vencimento</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{data.deadlines.map(r => <TableRow key={r.id}><TableCell className="font-medium">{r.tipo_codigo || "—"}</TableCell><TableCell>{r.descricao || "—"}</TableCell><TableCell>{formatDate(r.data_vencimento)}</TableCell><TableCell><StatusBadge value={SITUACAO_LABEL[situacaoVencimento(r.data_vencimento, r.status)]} /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
    <TabsContent value="manutencao"><SimpleRows rows={data.maintenance.map(r => [r.id, r.tipo || "Manutenção", r.problema || "—", formatDate(r.data_abertura), r.status])} /></TabsContent>
    <TabsContent value="sinistros"><SimpleRows rows={data.claims.map(r => [r.id, r.tipo || "Sinistro", r.local || "—", formatDate(r.data), r.status])} /></TabsContent>
    <TabsContent value="ficha"><Card className="rounded-lg"><CardContent className="grid gap-5 p-6 sm:grid-cols-2">{data.technical ? [["Identificação", data.technical.identificacao], ["Modelo", data.technical.modelo], ["Comprimento", data.technical.comprimento], ["Altura", data.technical.altura], ["Largura", data.technical.largura], ["Observações", data.technical.observacoes]].map(([l, x]) => <div key={String(l)}><p className="text-xs font-medium uppercase text-muted-foreground">{l}</p><p className="mt-1 text-sm">{x || "—"}</p></div>) : <p className="text-sm text-muted-foreground">Nenhuma ficha técnica vinculada.</p>}</CardContent></Card></TabsContent>
    <TabsContent value="historico"><Card className="rounded-lg"><CardContent className="divide-y p-6">{data.history.length ? data.history.map(h => <div key={h.id} className="py-4 first:pt-0"><div className="flex justify-between gap-3"><p className="text-sm font-semibold">{h.acao} {h.campo ? `· ${h.campo}` : ""}</p><span className="text-xs text-muted-foreground">{formatDateTime(h.created_at)}</span></div><p className="mt-1 text-sm text-muted-foreground">{h.valor_anterior || "—"} → {h.valor_novo || "—"}</p></div>) : <p className="text-sm text-muted-foreground">Nenhuma alteração registrada.</p>}</CardContent></Card></TabsContent>
    <TabsContent value="anexos"><Card className="rounded-lg"><CardContent className="p-6">{data.files.length ? data.files.map(f => <div key={f.id} className="flex items-center gap-3 border-b py-3 last:border-0"><Paperclip className="size-4 text-primary" /><div><p className="text-sm font-medium">{f.nome}</p><p className="text-xs text-muted-foreground">{f.tipo || "Arquivo"} · {formatDateTime(f.created_at)}</p></div></div>) : <p className="text-sm text-muted-foreground">Nenhum anexo vinculado.</p>}</CardContent></Card></TabsContent>
  </Tabs></>;
}

function SimpleRows({ rows }: { rows: Array<[string, string, string, string, string]> }) { return <Card className="rounded-lg"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Tipo</TableHead><TableHead>Descrição</TableHead><TableHead>Data</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{rows.map(r => <TableRow key={r[0]}><TableCell className="font-medium">{r[1]}</TableCell><TableCell>{r[2]}</TableCell><TableCell>{r[3]}</TableCell><TableCell><StatusBadge value={r[4]} /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>; }